name: CI

# run-name: executed by ${{ github.actor }} 

on:
  workflow_dispatch:    
  push:
    branches: [ "master" ]
  # pull_request:
  #   branches: [ "master" ]

jobs:

  test:
    
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Install NodeJS
      uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: ~/.npm
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      run: npm ci
    # - name: Run tests
    #   run: npm run test-ci

  build:
    needs: test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Install NodeJS
      uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: ~/.npm
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}        
    - name: Install dependencies
      run: npm ci
    - name: Build frontend
      run: npm run build
    - name: upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-files
        path: build
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps: 
      - name: Get build artifacts 
        uses: actions/download-artifact@v4
        with:
          name: build-files
      - name: Output contents
        run: ls
      # - name: Deploy


  build_docker_image:
    # needs: test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    # - name: Build Docker image
    #   run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to GitHub Docker Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/react-frontend:latest
          ghcr.io/${{ github.repository_owner }}/react-frontend:${{ github.sha }}

  